### PR TITLE
Access Control style.

### PR DESCRIPTION
**Pull request by hernangonzalez**
Proposal to use a documented protocol to define the class public interface.

### CODE REVIEW

**Comment by rafaelks** [comment]
Looks good!

**Comment by rafaelks** [comment]
I've a few thoughts about it... every class that have public methods (and properties) will need to have a protocol?

I'm not sure that we need this, since `public` and `private` exists to not have a *Interface* into the class. This can turn into extra work to maintain the code after a while, since someone can remove a public method from the protocol and have a public method into the class.

**Comment by hernangonzalez** [comment]
IMHO, it is the same as we do now with a header file.

And a class without a single public method might not be that useful lol

**Comment by hernangonzalez** [comment]
@rafaelks do you have a proposal to avoid going through 500 lines of code to see which methods are public or not?

**Comment by rafaelks** [comment]
@hernangonzalez Yes, but Swift is suppose to work different, that's why it doesn't have header files lol!

My suggestion is that you don't wanna see "What are public methods of MyClass?". You wanna look if *some* method is public or not. By using `MARK` and code documentation that's pretty easy to find it.

My only concern in creating a protocol to each class is the extra work that we're adding, since Swift is suppose to work by using the access control attributes.

**Pull request closed without merging**
